# Generated by Django 3.1.2 on 2021-01-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_sm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sm',
        ),
    ]
