# Generated by Django 3.1.2 on 2021-01-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_delete_sm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='slag',
            new_name='slug',
        ),
    ]
