# Generated by Django 3.1.2 on 2021-01-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210120_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='slug',
            new_name='slag',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='slug',
            new_name='slag',
        ),
    ]
