# Generated by Django 3.1.2 on 2021-01-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210120_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='notebook',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='slag',
            new_name='slug',
        ),
    ]
