# Generated by Django 3.1.2 on 2021-01-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210121_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymus_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
