# Generated by Django 3.1.2 on 2021-01-26 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210122_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='фото')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('display', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('resolution', models.CharField(max_length=255, verbose_name='Разрешение экрана')),
                ('smart_tv', models.BooleanField(default=True, verbose_name='Наличие смарт тв')),
                ('os_smart_tv', models.CharField(blank=True, max_length=255, null=True, verbose_name='Операционная система смарт')),
                ('wifi', models.BooleanField(default=True, verbose_name='Наличие беспроводного интернета')),
                ('bonus', models.BooleanField(default=True, verbose_name='Наличие бонусных подписок')),
                ('bonus_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Какие именно подписки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
